theme = "nightfox"
[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
H = "goto_line_start"
L = "goto_line_end"

[keys.select]
H = "goto_line_start"
L = "goto_line_end"