theme = "nightfox"
[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple" # make tabs apper once we have multiple buffers

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
H = "goto_line_start"
L = "goto_line_end"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
esc = ["collapse_selection", "keep_primary_selection"]
