theme = "nightfox"
[editor]
line-number = "relative"
cursorline = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

### keybinding ###

# normal mode
[keys.normal]
H = "goto_line_start"
L = "goto_line_end"
y = [":clipboard-yank", "yank"]
esc = ["collapse_selection", "keep_primary_selection"]

# "my" mode
[keys.normal."0"]
w = ":w"
q = ":q"
c = ":buffer-close"
t = [":w", ":sh hx-run.sh main.typ"]
l = [":w", ":sh hx-run.sh main.tex"]

# insert mode
[keys.insert]
A-w = ":buffer-close"

# select mode
[keys.select]
H = "goto_line_start"
y = [":clipboard-yank", "yank"]
L = "goto_line_end"
esc = ["collapse_selection", "keep_primary_selection"]
