require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.completions")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
--require("user.comment") do not use this module while nvim's version is 0.6. Otherwise it will break
